scan_timeout = 1000
command_timeout = 5000

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#007972)\
[  ](bg:#007972 fg:#001a22)\
[](bg:#005c57 fg:#007972)\
$directory\
[](fg:#005c57 bg:#003540)\
$git_branch\
$git_status\
[](fg:#003540 bg:#001f28)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#001f28 bg:#001a22)\
$time\
[ ](fg:#001a22)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#005c57"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#003540"
format = '[[ $symbol $branch ](fg:#b4fa72 bg:#003540)]($style)'

[git_status]
style = "bg:#003540"
format = '[[($all_status$ahead_behind )](fg:#b4fa72 bg:#003540)]($style)'

[nodejs]
symbol = ""
style = "bg:#001f28"
format = '[[ $symbol ($version) ](fg:#a5d5fe bg:#001f28)]($style)'

[rust]
symbol = ""
style = "bg:#001f28"
format = '[[ $symbol ($version) ](fg:#a5d5fe bg:#001f28)]($style)'

[golang]
symbol = ""
style = "bg:#001f28"
format = '[[ $symbol ($version) ](fg:#a5d5fe bg:#001f28)]($style)'

[php]
symbol = ""
style = "bg:#001f28"
format = '[[ $symbol ($version) ](fg:#a5d5fe bg:#001f28)]($style)'

[time]
disabled = false
time_format = "%d %b %I:%M %p"
style = "bg:#001a22"
format = '[[  $time ](fg:#007972 bg:#001a22)]($style)'

[character]
success_symbol = '[❯](bold #007972)'
error_symbol = '[❯](bold #ff8272)'
